<?php

function vcard_ocdi_import_files() {
    return array(
        array(
            'import_file_name'             => esc_attr__( 'Default', 'vcard' ),
            'categories'                   => array( esc_attr__( 'Main', 'vcard' ) ),
            'local_import_file'            => trailingslashit( get_template_directory() ) . 'demo/01/content.xml',
            'import_preview_image_url'     => get_template_directory_uri() . '/demo/01/preview.jpg',
            'preview_url'                  => esc_url( 'https://bslthemes.site/vcard/' ),
        ),
        array(
            'import_file_name'             => esc_attr__( 'Default Dark', 'vcard' ),
            'categories'                   => array( esc_attr__( 'Main', 'vcard' ) ),
            'local_import_file'            => trailingslashit( get_template_directory() ) . 'demo/02/content.xml',
            'import_preview_image_url'     => get_template_directory_uri() . '/demo/02/preview.jpg',
            'preview_url'                  => esc_url( 'https://bslthemes.site/vcard/dark' ),
        ),
        array(
            'import_file_name'             => esc_attr__( 'Alternative', 'vcard' ),
            'categories'                   => array( esc_attr__( 'Main', 'vcard' ) ),
            'local_import_file'            => trailingslashit( get_template_directory() ) . 'demo/03/content.xml',
            'import_preview_image_url'     => get_template_directory_uri() . '/demo/03/preview.jpg',
            'preview_url'                  => esc_url( 'https://bslthemes.site/vcard/alternative' ),
        ),
        array(
            'import_file_name'             => esc_attr__( 'Compact', 'vcard' ),
            'categories'                   => array( esc_attr__( 'Main', 'vcard' ) ),
            'local_import_file'            => trailingslashit( get_template_directory() ) . 'demo/04/content.xml',
            'import_preview_image_url'     => get_template_directory_uri() . '/demo/04/preview.jpg',
            'preview_url'                  => esc_url( 'https://bslthemes.site/vcard/compact' ),
        ),
        array(
            'import_file_name'             => esc_attr__( 'Compact Dark', 'vcard' ),
            'categories'                   => array( esc_attr__( 'Main', 'vcard' ) ),
            'local_import_file'            => trailingslashit( get_template_directory() ) . 'demo/05/content.xml',
            'import_preview_image_url'     => get_template_directory_uri() . '/demo/05/preview.jpg',
            'preview_url'                  => esc_url( 'https://bslthemes.site/vcard/compact_dark' ),
        ),
    );
}
add_filter( 'pt-ocdi/import_files', 'vcard_ocdi_import_files' );

function vcard_ocdi_after_import_setup( $selected_import ) {
    // Assign menus to their locations.
    $main_menu = get_term_by( 'name', 'Main Menu', 'nav_menu' );

    set_theme_mod( 'nav_menu_locations', array(
            'primary' => $main_menu->term_id,
        )
    );

    // Assign front page and posts page (blog page).
    $front_page_id = get_page_by_title( 'Home' );

    update_option( 'show_on_front', 'page' );
    update_option( 'page_on_front', $front_page_id->ID );
    update_option( 'posts_per_page', 6 );

    $ocdi_fields_static = array(
        'options_social_links' => '3',
        '_options_social_links' => 'field_5b68ccabc1b63',
        'options_vcard_info' => '5',
        '_options_vcard_info' => 'field_60a56f6620668',
        'options_vcard_btn' => '1',
        '_options_vcard_btn' => 'field_60a5857ce9291',
        'options_footer_text' => '© 2021 All Rights Reserved.',
        '_options_footer_text' => 'field_5b68cceac1b66',
        'options_blog_layout' => '1',
        '_options_blog_layout' => 'field_60a777dc8d967',
        'options_blog_categories' => '1',
        '_options_blog_categories' => 'field_5b81b6d930cb9',
        'options_blog_excerpt' => '0',
        '_options_blog_excerpt' => 'field_5b81b7ca30cba',
        'options_blog_featured_img' => '1',
        '_options_blog_featured_img' => 'field_5ee8e1ce18975',
        'options_social_share' => 'a:5:{i:0;s:8:"facebook";i:1;s:7:"twitter";i:2;s:8:"linkedin";i:3;s:6:"reddit";i:4;s:9:"pinterest";}',
        '_options_social_share' => 'field_5c610c399cf20',
        'options_p404_title' => 'Whoops!',
        '_options_p404_title' => 'field_5d180fd559b7f',
        'options_p404_content' => 'The page you\'re looking for doesn\'t exist or has been moved.',
        '_options_p404_content' => 'field_5d180feb59b80',
        'options_social_links_0_icon' => 'fab fa-facebook-f',
        '_options_social_links_0_icon' => 'field_5d879352bc7a2',
        'options_social_links_0_url' => 'https://facebook.com/',
        '_options_social_links_0_url' => 'field_5b68ccd7c1b65',
        'options_social_links_0_label' => 'Facebook',
        '_options_social_links_0_label' => 'field_60a56f4e20667',
        'options_social_links_1_icon' => 'fab fa-twitter',
        '_options_social_links_1_icon' => 'field_5d879352bc7a2',
        'options_social_links_1_url' => 'https://twitter.com/',
        '_options_social_links_1_url' => 'field_5b68ccd7c1b65',
        'options_social_links_1_label' => 'Twitter',
        '_options_social_links_1_label' => 'field_60a56f4e20667',
        'options_social_links_2_icon' => 'fab fa-instagram',
        '_options_social_links_2_icon' => 'field_5d879352bc7a2',
        'options_social_links_2_url' => 'https://instagram.com/',
        '_options_social_links_2_url' => 'field_5b68ccd7c1b65',
        'options_social_links_2_label' => 'Instagram',
        '_options_social_links_2_label' => 'field_60a56f4e20667',
        'options_vcard_info_0_icon_type' => '1',
        '_options_vcard_info_0_icon_type' => 'field_60a591d1d0a30',
        'options_vcard_info_0_icon_default' => 'calendar',
        '_options_vcard_info_0_icon_default' => 'field_60a591b5d0a2f',
        'options_vcard_info_0_text' => 'March 12, 1995',
        '_options_vcard_info_0_text' => 'field_60a56f882066c',
        'options_vcard_info_0_url' => '',
        '_options_vcard_info_0_url' => 'field_60a56f662066a',
        'options_vcard_info_0_label' => 'Birthday',
        '_options_vcard_info_0_label' => 'field_60a56f662066b',
        'options_vcard_info_1_icon_type' => '1',
        '_options_vcard_info_1_icon_type' => 'field_60a591d1d0a30',
        'options_vcard_info_1_icon_default' => 'location',
        '_options_vcard_info_1_icon_default' => 'field_60a591b5d0a2f',
        'options_vcard_info_1_text' => 'Hong Kong, China',
        '_options_vcard_info_1_text' => 'field_60a56f882066c',
        'options_vcard_info_1_url' => '',
        '_options_vcard_info_1_url' => 'field_60a56f662066a',
        'options_vcard_info_1_label' => 'Address',
        '_options_vcard_info_1_label' => 'field_60a56f662066b',
        'options_vcard_info_2_icon_type' => '1',
        '_options_vcard_info_2_icon_type' => 'field_60a591d1d0a30',
        'options_vcard_info_2_icon_default' => 'envelope',
        '_options_vcard_info_2_icon_default' => 'field_60a591b5d0a2f',
        'options_vcard_info_2_text' => 'example@mail.com',
        '_options_vcard_info_2_text' => 'field_60a56f882066c',
        'options_vcard_info_2_url' => 'mailto:example@mail.com',
        '_options_vcard_info_2_url' => 'field_60a56f662066a',
        'options_vcard_info_2_label' => 'Email',
        '_options_vcard_info_2_label' => 'field_60a56f662066b',
        'options_vcard_info_3_icon_type' => '1',
        '_options_vcard_info_3_icon_type' => 'field_60a591d1d0a30',
        'options_vcard_info_3_icon_default' => 'phone',
        '_options_vcard_info_3_icon_default' => 'field_60a591b5d0a2f',
        'options_vcard_info_3_text' => '+1 (070) 123-4567',
        '_options_vcard_info_3_text' => 'field_60a56f882066c',
        'options_vcard_info_3_url' => 'tel:+10701234567',
        '_options_vcard_info_3_url' => 'field_60a56f662066a',
        'options_vcard_info_3_label' => 'Phone',
        '_options_vcard_info_3_label' => 'field_60a56f662066b',
        'options_vcard_info_4_icon_type' => '1',
        '_options_vcard_info_4_icon_type' => 'field_60a591d1d0a30',
        'options_vcard_info_4_icon_default' => 'skype',
        '_options_vcard_info_4_icon_default' => 'field_60a591b5d0a2f',
        'options_vcard_info_4_url' => 'skype:Felecia_Brown',
        '_options_vcard_info_4_url' => 'field_60a56f662066a',
        'options_vcard_info_4_label' => 'Skype',
        '_options_vcard_info_4_label' => 'field_60a56f662066b',
        'options_vcard_btn_text' => 'Download CV',
        '_options_vcard_btn_text' => 'field_60a58597e9296',
        'options_vcard_btn_url' => 'https://drive.google.com/',
        '_options_vcard_btn_url' => 'field_60a585a8e9297',
    );
    $ocdi_fields_to_change = array();
    
    if( 'Default' === $selected_import['import_file_name'] ) {
        $ocdi_fields_to_change = array(
            'options_vcard_info_4_text' => 'Felecia_Brown',
            '_options_vcard_info_4_text' => 'field_60a56f882066c',
            'options_vcard_avatar' => '12',
            '_options_vcard_avatar' => 'field_5ed404ad72663',
            'options_vcard_fname' => 'Felecia',
            '_options_vcard_fname' => 'field_5ed3fef9ea45e',
            'options_vcard_lname' => 'Brown',
            '_options_vcard_lname' => 'field_60a43febba2e6',
            'options_vcard_role' => 'Creative Director',
            '_options_vcard_role' => 'field_60a576e6cd582',
            'options_theme_ui' => '1',
            '_options_theme_ui' => 'field_5f65e5ced5330',
            'options_theme_color' => '#304CFD',
            '_options_theme_color' => 'field_5b68d509665d9',
            'options_theme_bg_light_color' => '#f5f6f7',
            '_options_theme_bg_light_color' => 'field_5f65e6e2d5332',
            'options_heading_light_color' => '#44566c',
            '_options_heading_light_color' => 'field_5f65e70cd5333',
            'options_text_light_color' => '#44566c',
            '_options_text_light_color' => 'field_5f65e755d5334',
            'options_heading_font_family' => '0',
            '_options_heading_font_family' => 'field_5b68cfc4906fc',
            'options_text_font_family' => '0',
            '_options_text_font_family' => 'field_5b68d188906fd',
            'options_heading_font_size' => '',
            '_options_heading_font_size' => 'field_5eea66185ad1d',
            'options_text_font_size' => '',
            '_options_text_font_size' => 'field_5eea66ad5ad1e',
            'options_menu_font_size' => '',
            '_options_menu_font_size' => 'field_5eea67685ad1f',
            'options_menu_font_light_color' => '',
            '_options_menu_font_light_color' => 'field_5f65e77cd5335',
            'options_menu_font_family' => '0',
            '_options_menu_font_family' => 'field_5eea67ef5ad21',
            'options_menu_type' => '0',
            '_options_menu_type' => 'field_60a6c99c6c0e6',
            'options_bg_type' => '4',
            '_options_bg_type' => 'field_60a666a763016',
            'options_bg_objects' => '0',
            '_options_bg_objects' => 'field_60a667a9bdc8a',
            'options_theme_bg_color' => '#272333',
            '_options_theme_bg_color' => 'field_5f65e689d5331',
            'options_heading_color' => '#FFFFFF',
            '_options_heading_color' => 'field_5b68d5d8665da',
            'options_text_color' => '#dedde0',
            '_options_text_color' => 'field_5b68d617665db',
            'options_menu_font_color' => '',
            '_options_menu_font_color' => 'field_5eea679c5ad20',
        );
    }

    if( 'Default Dark' === $selected_import['import_file_name'] ) {
        $ocdi_fields_to_change = array(
            'options_vcard_avatar' => '16',
            '_options_vcard_avatar' => 'field_5ed404ad72663',
            'options_vcard_fname' => 'Thomas',
            '_options_vcard_fname' => 'field_5ed3fef9ea45e',
            'options_vcard_lname' => 'Castro',
            '_options_vcard_lname' => 'field_60a43febba2e6',
            'options_vcard_role' => 'Web Developer',
            '_options_vcard_role' => 'field_60a576e6cd582',
            'options_vcard_info_4_text' => 'Thomas_Castro',
            '_options_vcard_info_4_text' => 'field_60a56f882066c',
            'options_theme_ui' => '0',
            '_options_theme_ui' => 'field_5f65e5ced5330',
            'options_theme_color' => '#f07138',
            '_options_theme_color' => 'field_5b68d509665d9',
            'options_theme_bg_light_color' => '#f5f6f7',
            '_options_theme_bg_light_color' => 'field_5f65e6e2d5332',
            'options_heading_light_color' => '#44566c',
            '_options_heading_light_color' => 'field_5f65e70cd5333',
            'options_text_light_color' => '#44566c',
            '_options_text_light_color' => 'field_5f65e755d5334',
            'options_heading_font_family' => '0',
            '_options_heading_font_family' => 'field_5b68cfc4906fc',
            'options_text_font_family' => '0',
            '_options_text_font_family' => 'field_5b68d188906fd',
            'options_heading_font_size' => '',
            '_options_heading_font_size' => 'field_5eea66185ad1d',
            'options_text_font_size' => '',
            '_options_text_font_size' => 'field_5eea66ad5ad1e',
            'options_menu_font_size' => '',
            '_options_menu_font_size' => 'field_5eea67685ad1f',
            'options_menu_font_light_color' => '',
            '_options_menu_font_light_color' => 'field_5f65e77cd5335',
            'options_menu_font_family' => '0',
            '_options_menu_font_family' => 'field_5eea67ef5ad21',
            'options_menu_type' => '0',
            '_options_menu_type' => 'field_60a6c99c6c0e6',
            'options_bg_type' => '4',
            '_options_bg_type' => 'field_60a666a763016',
            'options_bg_objects' => '0',
            '_options_bg_objects' => 'field_60a667a9bdc8a',
            'options_theme_bg_color' => '#272333',
            '_options_theme_bg_color' => 'field_5f65e689d5331',
            'options_heading_color' => '#FFFFFF',
            '_options_heading_color' => 'field_5b68d5d8665da',
            'options_text_color' => '#dedde0',
            '_options_text_color' => 'field_5b68d617665db',
            'options_menu_font_color' => '',
            '_options_menu_font_color' => 'field_5eea679c5ad20',
        );
    }

    if( 'Alternative' === $selected_import['import_file_name'] ) {
        $ocdi_fields_to_change = array(
            'options_vcard_avatar' => '15',
            '_options_vcard_avatar' => 'field_5ed404ad72663',
            'options_vcard_fname' => 'Morgan',
            '_options_vcard_fname' => 'field_5ed3fef9ea45e',
            'options_vcard_lname' => 'Grant',
            '_options_vcard_lname' => 'field_60a43febba2e6',
            'options_vcard_role' => 'Creative Director',
            '_options_vcard_role' => 'field_60a576e6cd582',
            'options_vcard_info_4_text' => 'Morgan_Grant',
            '_options_vcard_info_4_text' => 'field_60a56f882066c',
            'options_theme_ui' => '1',
            '_options_theme_ui' => 'field_5f65e5ced5330',
            'options_theme_color' => '#304CFD',
            '_options_theme_color' => 'field_5b68d509665d9',
            'options_theme_bg_light_color' => '#f5f6f7',
            '_options_theme_bg_light_color' => 'field_5f65e6e2d5332',
            'options_heading_light_color' => '#44566c',
            '_options_heading_light_color' => 'field_5f65e70cd5333',
            'options_text_light_color' => '#44566c',
            '_options_text_light_color' => 'field_5f65e755d5334',
            'options_heading_font_family' => '0',
            '_options_heading_font_family' => 'field_5b68cfc4906fc',
            'options_text_font_family' => '0',
            '_options_text_font_family' => 'field_5b68d188906fd',
            'options_heading_font_size' => '',
            '_options_heading_font_size' => 'field_5eea66185ad1d',
            'options_text_font_size' => '',
            '_options_text_font_size' => 'field_5eea66ad5ad1e',
            'options_menu_font_size' => '',
            '_options_menu_font_size' => 'field_5eea67685ad1f',
            'options_menu_font_light_color' => '',
            '_options_menu_font_light_color' => 'field_5f65e77cd5335',
            'options_menu_font_family' => '0',
            '_options_menu_font_family' => 'field_5eea67ef5ad21',
            'options_menu_type' => '1',
            '_options_menu_type' => 'field_60a6c99c6c0e6',
            'options_bg_type' => '4',
            '_options_bg_type' => 'field_60a666a763016',
            'options_bg_objects' => '1',
            '_options_bg_objects' => 'field_60a667a9bdc8a',
            'options_theme_bg_color' => '#272333',
            '_options_theme_bg_color' => 'field_5f65e689d5331',
            'options_heading_color' => '#FFFFFF',
            '_options_heading_color' => 'field_5b68d5d8665da',
            'options_text_color' => '#dedde0',
            '_options_text_color' => 'field_5b68d617665db',
            'options_menu_font_color' => '',
            '_options_menu_font_color' => 'field_5eea679c5ad20',
        );
    }

    if( 'Compact' === $selected_import['import_file_name'] ) {
        $ocdi_fields_to_change = array(
            'options_vcard_info_4_text' => 'Felecia_Brown',
            '_options_vcard_info_4_text' => 'field_60a56f882066c',
            'options_vcard_avatar' => '12',
            '_options_vcard_avatar' => 'field_5ed404ad72663',
            'options_vcard_fname' => 'Felecia',
            '_options_vcard_fname' => 'field_5ed3fef9ea45e',
            'options_vcard_lname' => 'Brown',
            '_options_vcard_lname' => 'field_60a43febba2e6',
            'options_vcard_role' => 'Creative Director',
            '_options_vcard_role' => 'field_60a576e6cd582',
            'options_theme_ui' => '1',
            '_options_theme_ui' => 'field_5f65e5ced5330',
            'options_theme_style' => '1',
            '_options_theme_style' => 'field_60f2c06844e04',
            'options_theme_color' => '#304CFD',
            '_options_theme_color' => 'field_5b68d509665d9',
            'options_theme_bg_light_color' => '#f5f6f7',
            '_options_theme_bg_light_color' => 'field_5f65e6e2d5332',
            'options_heading_light_color' => '#44566c',
            '_options_heading_light_color' => 'field_5f65e70cd5333',
            'options_text_light_color' => '#44566c',
            '_options_text_light_color' => 'field_5f65e755d5334',
            'options_heading_font_family' => '0',
            '_options_heading_font_family' => 'field_5b68cfc4906fc',
            'options_text_font_family' => '0',
            '_options_text_font_family' => 'field_5b68d188906fd',
            'options_heading_font_size' => '',
            '_options_heading_font_size' => 'field_5eea66185ad1d',
            'options_text_font_size' => '',
            '_options_text_font_size' => 'field_5eea66ad5ad1e',
            'options_menu_font_size' => '',
            '_options_menu_font_size' => 'field_5eea67685ad1f',
            'options_menu_font_light_color' => '',
            '_options_menu_font_light_color' => 'field_5f65e77cd5335',
            'options_menu_font_family' => '0',
            '_options_menu_font_family' => 'field_5eea67ef5ad21',
            'options_menu_type' => '1',
            '_options_menu_type' => 'field_60a6c99c6c0e6',
            'options_bg_type' => '4',
            '_options_bg_type' => 'field_60a666a763016',
            'options_bg_objects' => '0',
            '_options_bg_objects' => 'field_60a667a9bdc8a',
            'options_theme_bg_color' => '#272333',
            '_options_theme_bg_color' => 'field_5f65e689d5331',
            'options_heading_color' => '#FFFFFF',
            '_options_heading_color' => 'field_5b68d5d8665da',
            'options_text_color' => '#dedde0',
            '_options_text_color' => 'field_5b68d617665db',
            'options_menu_font_color' => '',
            '_options_menu_font_color' => 'field_5eea679c5ad20',
        );
    }

    if( 'Compact Dark' === $selected_import['import_file_name'] ) {
        $ocdi_fields_to_change = array(
            'options_vcard_avatar' => '16',
            '_options_vcard_avatar' => 'field_5ed404ad72663',
            'options_vcard_fname' => 'Thomas',
            '_options_vcard_fname' => 'field_5ed3fef9ea45e',
            'options_vcard_lname' => 'Castro',
            '_options_vcard_lname' => 'field_60a43febba2e6',
            'options_vcard_role' => 'Web Developer',
            '_options_vcard_role' => 'field_60a576e6cd582',
            'options_vcard_info_4_text' => 'Thomas_Castro',
            '_options_vcard_info_4_text' => 'field_60a56f882066c',
            'options_theme_ui' => '0',
            '_options_theme_ui' => 'field_5f65e5ced5330',
            'options_theme_style' => '1',
            '_options_theme_style' => 'field_60f2c06844e04',
            'options_theme_color' => '#f07138',
            '_options_theme_color' => 'field_5b68d509665d9',
            'options_theme_bg_light_color' => '#f5f6f7',
            '_options_theme_bg_light_color' => 'field_5f65e6e2d5332',
            'options_heading_light_color' => '#44566c',
            '_options_heading_light_color' => 'field_5f65e70cd5333',
            'options_text_light_color' => '#44566c',
            '_options_text_light_color' => 'field_5f65e755d5334',
            'options_heading_font_family' => '0',
            '_options_heading_font_family' => 'field_5b68cfc4906fc',
            'options_text_font_family' => '0',
            '_options_text_font_family' => 'field_5b68d188906fd',
            'options_heading_font_size' => '',
            '_options_heading_font_size' => 'field_5eea66185ad1d',
            'options_text_font_size' => '',
            '_options_text_font_size' => 'field_5eea66ad5ad1e',
            'options_menu_font_size' => '',
            '_options_menu_font_size' => 'field_5eea67685ad1f',
            'options_menu_font_light_color' => '',
            '_options_menu_font_light_color' => 'field_5f65e77cd5335',
            'options_menu_font_family' => '0',
            '_options_menu_font_family' => 'field_5eea67ef5ad21',
            'options_menu_type' => '1',
            '_options_menu_type' => 'field_60a6c99c6c0e6',
            'options_bg_type' => '4',
            '_options_bg_type' => 'field_60a666a763016',
            'options_bg_objects' => '0',
            '_options_bg_objects' => 'field_60a667a9bdc8a',
            'options_theme_bg_color' => '#272333',
            '_options_theme_bg_color' => 'field_5f65e689d5331',
            'options_heading_color' => '#FFFFFF',
            '_options_heading_color' => 'field_5b68d5d8665da',
            'options_text_color' => '#dedde0',
            '_options_text_color' => 'field_5b68d617665db',
            'options_menu_font_color' => '',
            '_options_menu_font_color' => 'field_5eea679c5ad20',
        );
    }

    global $wpdb;
    foreach ( array_merge( $ocdi_fields_static, $ocdi_fields_to_change ) as $field => $value ) {
        if ( $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM $wpdb->options WHERE option_name = %s", $field ) ) == 0 ) {
            $wpdb->query( $wpdb->prepare( "INSERT INTO $wpdb->options ( option_name, option_value, autoload ) VALUES (%s, %s, 'no')", $field, $value ) );
        } else {
            $wpdb->query( $wpdb->prepare( "UPDATE $wpdb->options SET option_value = %s WHERE option_name = %s", $value, $field ) );
        }
    }

}
add_action( 'pt-ocdi/after_import', 'vcard_ocdi_after_import_setup' );